// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qoVKgVQ2sZgJYceYTt4HBN
// Component: 0uHPrPjRgUEj

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Header2 from "../../Header2"; // plasmic-import: lRRYlml6CT8h/component
import ProductCard from "../../ProductCard"; // plasmic-import: nedX9tcXfvMr/component
import Ratings from "../../Ratings"; // plasmic-import: ts7fEiC7or6S/component
import FeatureItem from "../../FeatureItem"; // plasmic-import: molQgoumCOqo/component
import BlogPost from "../../BlogPost"; // plasmic-import: hCjwnJbIqQ4X/component
import Footer from "../../Footer"; // plasmic-import: 7SaKjBtxTH88/component
import ProductRow from "../../ProductRow"; // plasmic-import: qZw1WdosKhVJ/component

import { useScreenVariants as useScreenVariantsnObOIahJqV6L } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: nObOIahJqV6L/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic.module.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: qoVKgVQ2sZgJYceYTt4HBN/projectcss
import sty from "./PlasmicStore.module.css"; // plasmic-import: 0uHPrPjRgUEj/css

import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: BTQ5d-_d3Bcp/icon
import Icon2Icon from "./icons/PlasmicIcon__Icon2"; // plasmic-import: SKCZk1ec-NIA/icon

createPlasmicElementProxy;

export type PlasmicStore__VariantMembers = {};
export type PlasmicStore__VariantsArgs = {};
type VariantPropType = keyof PlasmicStore__VariantsArgs;
export const PlasmicStore__VariantProps = new Array<VariantPropType>();

export type PlasmicStore__ArgsType = {};
type ArgPropType = keyof PlasmicStore__ArgsType;
export const PlasmicStore__ArgProps = new Array<ArgPropType>();

export type PlasmicStore__OverridesType = {
  root?: Flex__<"div">;
  header?: Flex__<"div">;
  header2?: Flex__<typeof Header2>;
  featureItem?: Flex__<typeof FeatureItem>;
  allProduct?: Flex__<"div">;
  bigPlants?: Flex__<"div">;
  cactuses?: Flex__<"div">;
  bestSellers?: Flex__<"div">;
  productRow?: Flex__<typeof ProductRow>;
};

export interface DefaultStoreProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicStore__RenderFunc(props: {
  variants: PlasmicStore__VariantsArgs;
  args: PlasmicStore__ArgsType;
  overrides: PlasmicStore__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $translator = usePlasmicTranslator?.();

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsnObOIahJqV6L()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_library_plasmic_color_type_css.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames(projectcss.all, sty.header)}
          >
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__yOKl1)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__yhq1C)}>
                <Header2
                  data-plasmic-name={"header2"}
                  data-plasmic-override={overrides.header2}
                  className={classNames("__wab_instance", sty.header2)}
                />
              </div>
            </Stack__>
            <div className={classNames(projectcss.all, sty.freeBox__uJgTn)}>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__cokYs
                )}
              >
                <Trans__>{"Top Collections"}</Trans__>
              </h2>
            </div>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__ohOrj)}
            >
              <div className={classNames(projectcss.all, sty.column__xhnIf)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__jsh6X
                  )}
                  image={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__hrBcE)}
                      displayHeight={"100%"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: "/plasmic/padungsilpa_website/images/galinaNMiziNqvJx5MUnsplashJpg.jpg",
                        fullWidth: 1920,
                        fullHeight: 1278,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  onSale={true}
                  price={<Trans__>{"$65.00"}</Trans__>}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__t7XC1
                      )}
                      numReviews={<Trans__>{"(45 Review)"}</Trans__>}
                    />
                  }
                  title={<Trans__>{"Product"}</Trans__>}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__cjfo)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__kh1Vw
                  )}
                  image={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__u6Mtf)}
                      displayHeight={"100%"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: "/plasmic/padungsilpa_website/images/igorSonFvPxCqgtwcUnsplashJpg.jpg",
                        fullWidth: 640,
                        fullHeight: 481,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  onSale={true}
                  price={<Trans__>{"$80.00"}</Trans__>}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__zfE3Z
                      )}
                      numReviews={<Trans__>{"(45 Review)"}</Trans__>}
                    />
                  }
                  title={<Trans__>{"Product"}</Trans__>}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__taCbj)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__pfcuC
                  )}
                  image={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__tlq3)}
                      displayHeight={"100%"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: "/plasmic/padungsilpa_website/images/scottWebbORwRlTgBrPoUnsplashJpg.jpg",
                        fullWidth: 1920,
                        fullHeight: 1280,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  price={<Trans__>{"$40.00"}</Trans__>}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__dyvl0
                      )}
                      numReviews={<Trans__>{"(45 Review)"}</Trans__>}
                    />
                  }
                  title={<Trans__>{"Product"}</Trans__>}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column___3QaCb)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__t6Hb
                  )}
                  image={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img___8FQuR)}
                      displayHeight={"100%"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: "/plasmic/padungsilpa_website/images/freddieMarriageUcfKyTanLuUnsplashJpg.jpg",
                        fullWidth: 640,
                        fullHeight: 427,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  onSale={true}
                  price={<Trans__>{"$100.00"}</Trans__>}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings___3DoXb
                      )}
                      numReviews={<Trans__>{"(45 Review)"}</Trans__>}
                    />
                  }
                  title={<Trans__>{"Product"}</Trans__>}
                />
              </div>
            </Stack__>
            <FeatureItem
              data-plasmic-name={"featureItem"}
              data-plasmic-override={overrides.featureItem}
              className={classNames("__wab_instance", sty.featureItem)}
            />

            <div className={classNames(projectcss.all, sty.freeBox__lV7Vo)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__cOzNa
                )}
              >
                <Trans__>{"Featured Products"}</Trans__>
              </div>
            </div>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__ruv2C)}
            >
              <div className={classNames(projectcss.all, sty.column__ipu8Z)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard___82Ebe
                  )}
                  price={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__mgdYs
                      )}
                    >
                      <Trans__>{"$160.00"}</Trans__>
                    </div>
                  }
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings___5AnFu
                      )}
                      numReviews={<Trans__>{"(12 Review)"}</Trans__>}
                      stars={"two"}
                    />
                  }
                  title={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__x8JSm
                      )}
                    >
                      <Trans__>{"Designed Sofa"}</Trans__>
                    </div>
                  }
                  withReviews={true}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__xlrQ0)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard___7Svpf
                  )}
                  image={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img___0KSMl)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: "/plasmic/padungsilpa_website/images/f2.jpg",
                        fullWidth: 270,
                        fullHeight: 310,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  price={<Trans__>{"$200.00"}</Trans__>}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__iiJLg
                      )}
                      stars={"four"}
                    />
                  }
                  title={<Trans__>{"Dining Table"}</Trans__>}
                  withReviews={true}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__bB3Pt)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__prdi8
                  )}
                  image={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__fGn0Q)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: "/plasmic/padungsilpa_website/images/f3.jpg",
                        fullWidth: 270,
                        fullHeight: 310,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  price={<Trans__>{"$100.00"}</Trans__>}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__pnNmr
                      )}
                      numReviews={<Trans__>{"(23 Review)"}</Trans__>}
                      stars={"five"}
                    />
                  }
                  title={<Trans__>{"Chair and Table"}</Trans__>}
                  withReviews={true}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__ifFcn)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__lgDjR
                  )}
                  image={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img___5JhBh)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: "/plasmic/padungsilpa_website/images/f4.jpg",
                        fullWidth: 270,
                        fullHeight: 310,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  price={<Trans__>{"$299.00"}</Trans__>}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__cfNtr
                      )}
                      numReviews={<Trans__>{"(35 Review)"}</Trans__>}
                    />
                  }
                  title={<Trans__>{"Modern Arm Chair"}</Trans__>}
                  withReviews={true}
                />
              </div>
            </Stack__>
            <div className={classNames(projectcss.all, sty.freeBox__cYmva)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__yL2M
                )}
              >
                <Trans__>{"Latest Blog"}</Trans__>
              </div>
            </div>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__jQd4)}
            >
              <div className={classNames(projectcss.all, sty.column__mCgnc)}>
                <BlogPost
                  className={classNames("__wab_instance", sty.blogPost__nBcRg)}
                  image={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__buAnv)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: "/plasmic/padungsilpa_website/images/b1.jpg",
                        fullWidth: 370,
                        fullHeight: 250,
                        aspectRatio: undefined
                      }}
                    />
                  }
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__hJaim)}>
                <BlogPost
                  className={classNames("__wab_instance", sty.blogPost__yNFk)}
                  image={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__awd2S)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: "/plasmic/padungsilpa_website/images/b2.jpg",
                        fullWidth: 370,
                        fullHeight: 250,
                        aspectRatio: undefined
                      }}
                    />
                  }
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__mHoeG)}>
                <BlogPost
                  className={classNames("__wab_instance", sty.blogPost__neX3T)}
                  image={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__p3Ss)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: "/plasmic/padungsilpa_website/images/b3.jpg",
                        fullWidth: 370,
                        fullHeight: 250,
                        aspectRatio: undefined
                      }}
                    />
                  }
                />
              </div>
            </Stack__>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__dI27K)}
            >
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__z5ELf)}
                displayHeight={"60px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"90px"}
                src={{
                  src: "/plasmic/padungsilpa_website/images/adidas.png",
                  fullWidth: 90,
                  fullHeight: 60,
                  aspectRatio: undefined
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__edmMc)}
                displayHeight={"60px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"91px"}
                src={{
                  src: "/plasmic/padungsilpa_website/images/hm.png",
                  fullWidth: 91,
                  fullHeight: 60,
                  aspectRatio: undefined
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__d2Us)}
                displayHeight={"60px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"98px"}
                src={{
                  src: "/plasmic/padungsilpa_website/images/kappa.png",
                  fullWidth: 98,
                  fullHeight: 60,
                  aspectRatio: undefined
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__keI1)}
                displayHeight={"60px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"124px"}
                src={{
                  src: "/plasmic/padungsilpa_website/images/lacoste.png",
                  fullWidth: 124,
                  fullHeight: 60,
                  aspectRatio: undefined
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__yzybZ)}
                displayHeight={"60px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"125px"}
                src={{
                  src: "/plasmic/padungsilpa_website/images/levis.png",
                  fullWidth: 125,
                  fullHeight: 60,
                  aspectRatio: undefined
                }}
              />
            </Stack__>
            <Footer
              className={classNames("__wab_instance", sty.footer__bIAmE)}
            />
          </div>
          <div
            data-plasmic-name={"allProduct"}
            data-plasmic-override={overrides.allProduct}
            className={classNames(projectcss.all, sty.allProduct)}
          >
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__iwZft)}
            >
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__eEhSr
                )}
              >
                <Trans__>{"All Products"}</Trans__>
              </h2>
            </Stack__>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__ky7H6)}
            >
              <div className={classNames(projectcss.all, sty.column__o04Pi)}>
                <div className={classNames(projectcss.all, sty.freeBox__qM63)}>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__hw7Fw)}
                  >
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__tdsbi
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      <Trans__>{"Summer plants"}</Trans__>
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__iBrrt
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      <Trans__>{"Plants from Europe"}</Trans__>
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__m8QpT
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      <Trans__>{"Cactuses"}</Trans__>
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__d6EzF
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      <Trans__>{"Big plants"}</Trans__>
                    </PlasmicLink__>
                  </Stack__>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column___9FugM)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.columns___6Rbkp)}
                >
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.column__i5VxU)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__exesB)}
                      displayHeight={"270px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/padungsilpa_website/images/plant6Jpg.png",
                        fullWidth: 400,
                        fullHeight: 400,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__hhoel)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__fOeW3)}
                        role={"img"}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__ycMip)}
                    >
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__uKeFu
                        )}
                        component={Link}
                        platform={"nextjs"}
                      >
                        <Trans__>{"Donec finibus"}</Trans__>
                      </PlasmicLink__>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___1KyFf
                        )}
                      >
                        <Trans__>{"bigplants"}</Trans__>
                      </div>
                      <h5
                        className={classNames(
                          projectcss.all,
                          projectcss.h5,
                          projectcss.__wab_text,
                          sty.h5__pq1AG
                        )}
                      >
                        <Trans__>{"$100.00"}</Trans__>
                      </h5>
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.column__psWaA)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__rjJtB)}
                      displayHeight={"270px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/padungsilpa_website/images/plant1Jpg.png",
                        fullWidth: 400,
                        fullHeight: 400,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__praoY)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__y3Yon)}
                        role={"img"}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__cvqEr)}
                    >
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link___15DBd
                        )}
                        component={Link}
                        platform={"nextjs"}
                      >
                        <Trans__>{"Nulla suscipit"}</Trans__>
                      </PlasmicLink__>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___12FRs
                        )}
                      >
                        <Trans__>{"bigplants "}</Trans__>
                      </div>
                      <h5
                        className={classNames(
                          projectcss.all,
                          projectcss.h5,
                          projectcss.__wab_text,
                          sty.h5__z712F
                        )}
                      >
                        <Trans__>{"$49.40 "}</Trans__>
                      </h5>
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.column__j9FpP)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__mr87O)}
                      displayHeight={"270px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/padungsilpa_website/images/plant5Jpg.png",
                        fullWidth: 400,
                        fullHeight: 400,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__jkWwy)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__dBw4H)}
                        role={"img"}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__mG6NE)}
                    >
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__iZ7T1
                        )}
                        component={Link}
                        platform={"nextjs"}
                      >
                        <Trans__>{"Vestibulum eget"}</Trans__>
                      </PlasmicLink__>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__gmH6V
                        )}
                      >
                        <Trans__>{"bigplants "}</Trans__>
                      </div>
                      <h5
                        className={classNames(
                          projectcss.all,
                          projectcss.h5,
                          projectcss.__wab_text,
                          sty.h5__lyYS
                        )}
                      >
                        <Trans__>{"$220.40 "}</Trans__>
                      </h5>
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.column__bUrxC)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img___34Eei)}
                      displayHeight={"270px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/padungsilpa_website/images/plant7Jpg.png",
                        fullWidth: 400,
                        fullHeight: 400,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__brOdx)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__aMmzb)}
                        role={"img"}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__mzMcZ)}
                    >
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__ojBQe
                        )}
                        component={Link}
                        platform={"nextjs"}
                      >
                        <Trans__>{"Sed consectetur"}</Trans__>
                      </PlasmicLink__>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__uaVp
                        )}
                      >
                        <Trans__>{"bigplants "}</Trans__>
                      </div>
                      <h5
                        className={classNames(
                          projectcss.all,
                          projectcss.h5,
                          projectcss.__wab_text,
                          sty.h5__smU5A
                        )}
                      >
                        <Trans__>{"$18.40 "}</Trans__>
                      </h5>
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.column__tmcYa)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__i1Kur)}
                      displayHeight={"270px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/padungsilpa_website/images/plant6Jpg.png",
                        fullWidth: 400,
                        fullHeight: 400,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__tcg1)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__yhG2B)}
                        role={"img"}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__d7CL)}
                    >
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__gDOl
                        )}
                        component={Link}
                        platform={"nextjs"}
                      >
                        <Trans__>{"Donec finibus"}</Trans__>
                      </PlasmicLink__>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__bUmN
                        )}
                      >
                        <Trans__>{"bigplants"}</Trans__>
                      </div>
                      <h5
                        className={classNames(
                          projectcss.all,
                          projectcss.h5,
                          projectcss.__wab_text,
                          sty.h5__phWWv
                        )}
                      >
                        <Trans__>{"$100.00"}</Trans__>
                      </h5>
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.column__xv4Os)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__qqWtk)}
                      displayHeight={"270px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/padungsilpa_website/images/plant2Webp.webp",
                        fullWidth: 400,
                        fullHeight: 400,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__zbJdu)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__vuZvt)}
                        role={"img"}
                      />
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___9UaTu
                      )}
                    >
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__frwh
                        )}
                        component={Link}
                        platform={"nextjs"}
                      >
                        <Trans__>{"Integer porta"}</Trans__>
                      </PlasmicLink__>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__iGYmQ
                        )}
                      >
                        <Trans__>{"Cactuses"}</Trans__>
                      </div>
                      <h5
                        className={classNames(
                          projectcss.all,
                          projectcss.h5,
                          projectcss.__wab_text,
                          sty.h5__dpHy3
                        )}
                      >
                        <Trans__>{"$49.40 "}</Trans__>
                      </h5>
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.column__vLih6)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__zbnxf)}
                      displayHeight={"270px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/padungsilpa_website/images/plant41Jpg.png",
                        fullWidth: 400,
                        fullHeight: 400,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__yAXvp)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__nueJo)}
                        role={"img"}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox___9E90)}
                    >
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link___7BDg6
                        )}
                        component={Link}
                        platform={"nextjs"}
                      >
                        <Trans__>{"Cras molestie"}</Trans__>
                      </PlasmicLink__>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__dyZ4
                        )}
                      >
                        <Trans__>{"cactuses "}</Trans__>
                      </div>
                      <h5
                        className={classNames(
                          projectcss.all,
                          projectcss.h5,
                          projectcss.__wab_text,
                          sty.h5__sxiKn
                        )}
                      >
                        <Trans__>{"$24.99"}</Trans__>
                      </h5>
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.column__oxzry)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__d25Y)}
                      displayHeight={"270px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/padungsilpa_website/images/plant31Jpg.png",
                        fullWidth: 400,
                        fullHeight: 400,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__kj1BT)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__dMfRj)}
                        role={"img"}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__ob00I)}
                    >
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__yPzZb
                        )}
                        component={Link}
                        platform={"nextjs"}
                      >
                        <Trans__>{"Curabitur eu tempor"}</Trans__>
                      </PlasmicLink__>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__xOi98
                        )}
                      >
                        <Trans__>{"Cactuses"}</Trans__>
                      </div>
                      <h5
                        className={classNames(
                          projectcss.all,
                          projectcss.h5,
                          projectcss.__wab_text,
                          sty.h5__qOBbV
                        )}
                      >
                        <Trans__>{"$49.40 "}</Trans__>
                      </h5>
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.column__u4IAq)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__ho5Xa)}
                      displayHeight={"270px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/padungsilpa_website/images/plant9Webp.webp",
                        fullWidth: 400,
                        fullHeight: 400,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__mgXdJ)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__bRzO)}
                        role={"img"}
                      />
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___7UYre
                      )}
                    >
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__djKoj
                        )}
                        component={Link}
                        platform={"nextjs"}
                      >
                        <Trans__>{"Fusce sagittis"}</Trans__>
                      </PlasmicLink__>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__eseSr
                        )}
                      >
                        <Trans__>{"Cactuses"}</Trans__>
                      </div>
                      <h5
                        className={classNames(
                          projectcss.all,
                          projectcss.h5,
                          projectcss.__wab_text,
                          sty.h5__ly7Om
                        )}
                      >
                        <Trans__>{"$49.40 "}</Trans__>
                      </h5>
                    </div>
                  </Stack__>
                </Stack__>
              </div>
            </Stack__>
          </div>
          <Stack__
            as={"div"}
            data-plasmic-name={"bigPlants"}
            data-plasmic-override={overrides.bigPlants}
            hasGap={true}
            className={classNames(projectcss.all, sty.bigPlants)}
          >
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__sClK7)}
            >
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2___7PWiH
                )}
              >
                <Trans__>{"Big plants"}</Trans__>
              </h2>
            </Stack__>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__d1FS)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__s7Vty)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__ujwrW)}
                  displayHeight={"270px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/padungsilpa_website/images/plant6Jpg.png",
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__hmFtp)}>
                  <Icon3Icon
                    className={classNames(projectcss.all, sty.svg___1XXdV)}
                    role={"img"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__zBLcs)}>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link___7756M
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    <Trans__>{"Donec finibus"}</Trans__>
                  </PlasmicLink__>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__oHi4L
                    )}
                  >
                    <Trans__>{"bigplants"}</Trans__>
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__aGb8K
                    )}
                  >
                    <Trans__>{"$100.00"}</Trans__>
                  </h5>
                </div>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__wv4IL)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__fZb29)}
                  displayHeight={"270px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/padungsilpa_website/images/plant1Jpg.png",
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__zVqp9)}>
                  <Icon3Icon
                    className={classNames(projectcss.all, sty.svg___4HrNy)}
                    role={"img"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__vPgbc)}>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__vDNqf
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    <Trans__>{"Nulla suscipit"}</Trans__>
                  </PlasmicLink__>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__dYSr
                    )}
                  >
                    <Trans__>{"bigplants "}</Trans__>
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__lHbOh
                    )}
                  >
                    <Trans__>{"$49.40 "}</Trans__>
                  </h5>
                </div>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__hJ3Mj)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__kbAtq)}
                  displayHeight={"270px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/padungsilpa_website/images/plant7Jpg.png",
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__rnPa7)}>
                  <Icon3Icon
                    className={classNames(projectcss.all, sty.svg___19Dn6)}
                    role={"img"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__qi5GL)}>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__la9Z6
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    <Trans__>{"Sed consectetur"}</Trans__>
                  </PlasmicLink__>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__jrq6D
                    )}
                  >
                    <Trans__>{"bigplants "}</Trans__>
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__mUIk5
                    )}
                  >
                    <Trans__>{"$18.40 "}</Trans__>
                  </h5>
                </div>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__jeJs6)}
                  displayHeight={"270px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/padungsilpa_website/images/plant5Jpg.png",
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__gqzlb)}>
                  <Icon3Icon
                    className={classNames(projectcss.all, sty.svg__wckPq)}
                    role={"img"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__mWyFv)}>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__p7Wrj
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    <Trans__>{"Vestibulum eget"}</Trans__>
                  </PlasmicLink__>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ylhce
                    )}
                  >
                    <Trans__>{"bigplants "}</Trans__>
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__pcC5I
                    )}
                  >
                    <Trans__>{"$220.40 "}</Trans__>
                  </h5>
                </div>
              </Stack__>
            </Stack__>
          </Stack__>
          <Stack__
            as={"div"}
            data-plasmic-name={"cactuses"}
            data-plasmic-override={overrides.cactuses}
            hasGap={true}
            className={classNames(projectcss.all, sty.cactuses)}
          >
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__xbXcH)}
            >
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__rxuLc
                )}
              >
                <Trans__>{"Cactuses"}</Trans__>
              </h2>
            </Stack__>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__vc0Ez)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__vLCdE)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__k5V3Z)}
                  displayHeight={"270px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/padungsilpa_website/images/plant41Jpg.png",
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__h9ZwF)}>
                  <Icon3Icon
                    className={classNames(projectcss.all, sty.svg__doZa)}
                    role={"img"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__hs5Fh)}>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__fbYow
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    <Trans__>{"Cras molestie"}</Trans__>
                  </PlasmicLink__>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__kFjac
                    )}
                  >
                    <Trans__>{"cactuses "}</Trans__>
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__r6N93
                    )}
                  >
                    <Trans__>{"$24.99"}</Trans__>
                  </h5>
                </div>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__cY4F)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__d3Ygm)}
                  displayHeight={"270px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/padungsilpa_website/images/plant31Jpg.png",
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__cf1Cr)}>
                  <Icon3Icon
                    className={classNames(projectcss.all, sty.svg__riv09)}
                    role={"img"}
                  />
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox___7Bkq6)}
                >
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__fjNew
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    <Trans__>{"Curabitur eu tempor"}</Trans__>
                  </PlasmicLink__>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___82222
                    )}
                  >
                    <Trans__>{"Cactuses"}</Trans__>
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5___5Dc0N
                    )}
                  >
                    <Trans__>{"$49.40 "}</Trans__>
                  </h5>
                </div>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__kP4)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img___44LhX)}
                  displayHeight={"270px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/padungsilpa_website/images/plant9Webp.webp",
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                <div
                  className={classNames(projectcss.all, sty.freeBox___6KVb8)}
                >
                  <Icon3Icon
                    className={classNames(projectcss.all, sty.svg__ynPxg)}
                    role={"img"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__wI5A)}>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__plQvd
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    <Trans__>{"Fusce sagittis"}</Trans__>
                  </PlasmicLink__>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__okf2Y
                    )}
                  >
                    <Trans__>{"Fusce sagittis"}</Trans__>
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__mLgmp
                    )}
                  >
                    <Trans__>{"$49.40 "}</Trans__>
                  </h5>
                </div>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__xaxr4)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__i4VvQ)}
                  displayHeight={"270px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/padungsilpa_website/images/plant2Webp.webp",
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__wRz3U)}>
                  <Icon3Icon
                    className={classNames(projectcss.all, sty.svg__m3Hh)}
                    role={"img"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__xKYi7)}>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__wpcUb
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    <Trans__>{"Integer porta"}</Trans__>
                  </PlasmicLink__>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__sJpir
                    )}
                  >
                    <Trans__>{"Cactuses"}</Trans__>
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__dVf4
                    )}
                  >
                    <Trans__>{"$49.40 "}</Trans__>
                  </h5>
                </div>
              </Stack__>
            </Stack__>
          </Stack__>
          <Stack__
            as={"div"}
            data-plasmic-name={"bestSellers"}
            data-plasmic-override={overrides.bestSellers}
            hasGap={true}
            className={classNames(projectcss.all, sty.bestSellers)}
          >
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__wepS2)}
            >
              <Icon2Icon
                className={classNames(projectcss.all, sty.svg__lwqZg)}
                role={"img"}
              />

              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__arRng
                )}
              >
                <Trans__>{"Best sellers"}</Trans__>
              </h2>
            </Stack__>
            <ProductRow
              data-plasmic-name={"productRow"}
              data-plasmic-override={overrides.productRow}
              className={classNames("__wab_instance", sty.productRow)}
            />
          </Stack__>
          <Footer
            className={classNames("__wab_instance", sty.footer___88IbP)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "header",
    "header2",
    "featureItem",
    "allProduct",
    "bigPlants",
    "cactuses",
    "bestSellers",
    "productRow"
  ],
  header: ["header", "header2", "featureItem"],
  header2: ["header2"],
  featureItem: ["featureItem"],
  allProduct: ["allProduct"],
  bigPlants: ["bigPlants"],
  cactuses: ["cactuses"],
  bestSellers: ["bestSellers", "productRow"],
  productRow: ["productRow"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  header: "div";
  header2: typeof Header2;
  featureItem: typeof FeatureItem;
  allProduct: "div";
  bigPlants: "div";
  cactuses: "div";
  bestSellers: "div";
  productRow: typeof ProductRow;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicStore__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicStore__VariantsArgs;
    args?: PlasmicStore__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicStore__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicStore__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicStore__ArgProps,
          internalVariantPropNames: PlasmicStore__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicStore__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicStore";
  } else {
    func.displayName = `PlasmicStore.${nodeName}`;
  }
  return func;
}

export const PlasmicStore = Object.assign(
  // Top-level PlasmicStore renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    header2: makeNodeComponent("header2"),
    featureItem: makeNodeComponent("featureItem"),
    allProduct: makeNodeComponent("allProduct"),
    bigPlants: makeNodeComponent("bigPlants"),
    cactuses: makeNodeComponent("cactuses"),
    bestSellers: makeNodeComponent("bestSellers"),
    productRow: makeNodeComponent("productRow"),

    // Metadata about props expected for PlasmicStore
    internalVariantProps: PlasmicStore__VariantProps,
    internalArgProps: PlasmicStore__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicStore;
/* prettier-ignore-end */
