// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qoVKgVQ2sZgJYceYTt4HBN
// Component: dp87--8KP5H5

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Header2 from "../../Header2"; // plasmic-import: lRRYlml6CT8h/component
import ProductCard from "../../ProductCard"; // plasmic-import: nedX9tcXfvMr/component
import Ratings from "../../Ratings"; // plasmic-import: ts7fEiC7or6S/component
import FeatureItem from "../../FeatureItem"; // plasmic-import: molQgoumCOqo/component
import BlogPost from "../../BlogPost"; // plasmic-import: hCjwnJbIqQ4X/component
import Footer from "../../Footer"; // plasmic-import: 7SaKjBtxTH88/component
import MenuButton from "../../MenuButton"; // plasmic-import: vOCTxqL3X3fh/component

import { useScreenVariants as useScreenVariantsnObOIahJqV6L } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: nObOIahJqV6L/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic.module.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: qoVKgVQ2sZgJYceYTt4HBN/projectcss
import sty from "./PlasmicFaq.module.css"; // plasmic-import: dp87--8KP5H5/css

import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: BTQ5d-_d3Bcp/icon
import DotSvgrepoCom1SvgIcon from "./icons/PlasmicIcon__DotSvgrepoCom1Svg"; // plasmic-import: LfxddByqVv0F/icon
import LocationSvgrepoCom1SvgIcon from "./icons/PlasmicIcon__LocationSvgrepoCom1Svg"; // plasmic-import: 191HtaIkxTqt/icon
import LogoWhiteSvgIcon from "./icons/PlasmicIcon__LogoWhiteSvg"; // plasmic-import: ummb3XXmzwv1/icon

createPlasmicElementProxy;

export type PlasmicFaq__VariantMembers = {};
export type PlasmicFaq__VariantsArgs = {};
type VariantPropType = keyof PlasmicFaq__VariantsArgs;
export const PlasmicFaq__VariantProps = new Array<VariantPropType>();

export type PlasmicFaq__ArgsType = {};
type ArgPropType = keyof PlasmicFaq__ArgsType;
export const PlasmicFaq__ArgProps = new Array<ArgPropType>();

export type PlasmicFaq__OverridesType = {
  root?: Flex__<"div">;
  foreground2?: Flex__<"div">;
  header?: Flex__<"div">;
  featureItem?: Flex__<typeof FeatureItem>;
  bigPlants?: Flex__<"div">;
  cactuses?: Flex__<"div">;
  menuButton?: Flex__<typeof MenuButton>;
};

export interface DefaultFaqProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicFaq__RenderFunc(props: {
  variants: PlasmicFaq__VariantsArgs;
  args: PlasmicFaq__ArgsType;
  overrides: PlasmicFaq__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $translator = usePlasmicTranslator?.();

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsnObOIahJqV6L()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_library_plasmic_color_type_css.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__wKwTh)}>
            <Header2
              className={classNames("__wab_instance", sty.header2__qWvs0)}
            />

            <div className={classNames(projectcss.all, sty.freeBox__xzEr)}>
              <Stack__
                as={"div"}
                data-plasmic-name={"foreground2"}
                data-plasmic-override={overrides.foreground2}
                hasGap={true}
                className={classNames(projectcss.all, sty.foreground2)}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__j0HyJ)}
                >
                  <h1
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1__m2Fvm
                    )}
                  >
                    <Trans__>{"Behold our FAQ"}</Trans__>
                  </h1>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__xvaeV)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__fpbon
                      )}
                    >
                      <Trans__>
                        {hasVariant(globalVariants, "screen", "mobile")
                          ? "I didn't know the Snipcart guys were into herbs as well! How beautiful is that Planty theme. I'm going to launch a killer JAMstack e-commerce store using this for sure."
                          : "All right, friends. Let\u2019s do this. This section will cover basic, frequently asked questions for e-commerce merchants."}
                      </Trans__>
                    </div>
                  </div>
                </Stack__>
              </Stack__>
            </div>
          </div>
          <div
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames(projectcss.all, sty.header)}
          >
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__tp5Mc)}
            >
              <div className={classNames(projectcss.all, sty.freeBox___5OyKb)}>
                <Header2
                  className={classNames("__wab_instance", sty.header2__mlZYd)}
                />
              </div>
            </Stack__>
            <div className={classNames(projectcss.all, sty.freeBox__lnBo8)}>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2___7B21A
                )}
              >
                <Trans__>{"Top Collections"}</Trans__>
              </h2>
            </div>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns___2Z9D)}
            >
              <div className={classNames(projectcss.all, sty.column___9QNf)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__sWvXp
                  )}
                  image={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__kUqKj)}
                      displayHeight={"100%"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: "/plasmic/padungsilpa_website/images/galinaNMiziNqvJx5MUnsplashJpg.jpg",
                        fullWidth: 1920,
                        fullHeight: 1278,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  onSale={true}
                  price={<Trans__>{"$65.00"}</Trans__>}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__bNqi
                      )}
                      numReviews={<Trans__>{"(45 Review)"}</Trans__>}
                    />
                  }
                  title={<Trans__>{"Product"}</Trans__>}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column___5BMvM)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__nozYd
                  )}
                  image={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__dj6XW)}
                      displayHeight={"100%"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: "/plasmic/padungsilpa_website/images/igorSonFvPxCqgtwcUnsplashJpg.jpg",
                        fullWidth: 640,
                        fullHeight: 481,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  onSale={true}
                  price={<Trans__>{"$80.00"}</Trans__>}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__k40Sg
                      )}
                      numReviews={<Trans__>{"(45 Review)"}</Trans__>}
                    />
                  }
                  title={<Trans__>{"Product"}</Trans__>}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__vnEmm)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard___56CPs
                  )}
                  image={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__vROjP)}
                      displayHeight={"100%"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: "/plasmic/padungsilpa_website/images/scottWebbORwRlTgBrPoUnsplashJpg.jpg",
                        fullWidth: 1920,
                        fullHeight: 1280,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  price={<Trans__>{"$40.00"}</Trans__>}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings___6LGFq
                      )}
                      numReviews={<Trans__>{"(45 Review)"}</Trans__>}
                    />
                  }
                  title={<Trans__>{"Product"}</Trans__>}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__b5XxN)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__wc3GR
                  )}
                  image={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__odLvF)}
                      displayHeight={"100%"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: "/plasmic/padungsilpa_website/images/freddieMarriageUcfKyTanLuUnsplashJpg.jpg",
                        fullWidth: 640,
                        fullHeight: 427,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  onSale={true}
                  price={<Trans__>{"$100.00"}</Trans__>}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__zbbgs
                      )}
                      numReviews={<Trans__>{"(45 Review)"}</Trans__>}
                    />
                  }
                  title={<Trans__>{"Product"}</Trans__>}
                />
              </div>
            </Stack__>
            <FeatureItem
              data-plasmic-name={"featureItem"}
              data-plasmic-override={overrides.featureItem}
              className={classNames("__wab_instance", sty.featureItem)}
            />

            <div className={classNames(projectcss.all, sty.freeBox__czDw5)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__rGgb6
                )}
              >
                <Trans__>{"Featured Products"}</Trans__>
              </div>
            </div>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns___65Rt9)}
            >
              <div className={classNames(projectcss.all, sty.column__fibWo)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__yqoAf
                  )}
                  price={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___2M2Dk
                      )}
                    >
                      <Trans__>{"$160.00"}</Trans__>
                    </div>
                  }
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__qPwji
                      )}
                      numReviews={<Trans__>{"(12 Review)"}</Trans__>}
                      stars={"two"}
                    />
                  }
                  title={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__nfu9B
                      )}
                    >
                      <Trans__>{"Designed Sofa"}</Trans__>
                    </div>
                  }
                  withReviews={true}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__wMtYx)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__fn66W
                  )}
                  image={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__cXzUa)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: "/plasmic/padungsilpa_website/images/f2.jpg",
                        fullWidth: 270,
                        fullHeight: 310,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  price={<Trans__>{"$200.00"}</Trans__>}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings___21Imb
                      )}
                      stars={"four"}
                    />
                  }
                  title={<Trans__>{"Dining Table"}</Trans__>}
                  withReviews={true}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column___5Wqsh)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__nyYFl
                  )}
                  image={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__mAh7M)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: "/plasmic/padungsilpa_website/images/f3.jpg",
                        fullWidth: 270,
                        fullHeight: 310,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  price={<Trans__>{"$100.00"}</Trans__>}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__w5KKd
                      )}
                      numReviews={<Trans__>{"(23 Review)"}</Trans__>}
                      stars={"five"}
                    />
                  }
                  title={<Trans__>{"Chair and Table"}</Trans__>}
                  withReviews={true}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__xjTgU)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__nsZeQ
                  )}
                  image={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img___7Bpwt)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: "/plasmic/padungsilpa_website/images/f4.jpg",
                        fullWidth: 270,
                        fullHeight: 310,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  price={<Trans__>{"$299.00"}</Trans__>}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__hZ6Bc
                      )}
                      numReviews={<Trans__>{"(35 Review)"}</Trans__>}
                    />
                  }
                  title={<Trans__>{"Modern Arm Chair"}</Trans__>}
                  withReviews={true}
                />
              </div>
            </Stack__>
            <div className={classNames(projectcss.all, sty.freeBox__vKhVi)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___3AkJp
                )}
              >
                <Trans__>{"Latest Blog"}</Trans__>
              </div>
            </div>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__ebAmI)}
            >
              <div className={classNames(projectcss.all, sty.column__e1M7K)}>
                <BlogPost
                  className={classNames("__wab_instance", sty.blogPost__u96JP)}
                  image={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img___9GQwp)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: "/plasmic/padungsilpa_website/images/b1.jpg",
                        fullWidth: 370,
                        fullHeight: 250,
                        aspectRatio: undefined
                      }}
                    />
                  }
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__ppvAv)}>
                <BlogPost
                  className={classNames("__wab_instance", sty.blogPost___83Aac)}
                  image={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__k0If)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: "/plasmic/padungsilpa_website/images/b2.jpg",
                        fullWidth: 370,
                        fullHeight: 250,
                        aspectRatio: undefined
                      }}
                    />
                  }
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__a9Z7B)}>
                <BlogPost
                  className={classNames("__wab_instance", sty.blogPost__fnIhX)}
                  image={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__rnGr4)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: "/plasmic/padungsilpa_website/images/b3.jpg",
                        fullWidth: 370,
                        fullHeight: 250,
                        aspectRatio: undefined
                      }}
                    />
                  }
                />
              </div>
            </Stack__>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__xh5AJ)}
            >
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__oz7D5)}
                displayHeight={"60px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"90px"}
                src={{
                  src: "/plasmic/padungsilpa_website/images/adidas.png",
                  fullWidth: 90,
                  fullHeight: 60,
                  aspectRatio: undefined
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__d4F4K)}
                displayHeight={"60px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"91px"}
                src={{
                  src: "/plasmic/padungsilpa_website/images/hm.png",
                  fullWidth: 91,
                  fullHeight: 60,
                  aspectRatio: undefined
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__axkxd)}
                displayHeight={"60px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"98px"}
                src={{
                  src: "/plasmic/padungsilpa_website/images/kappa.png",
                  fullWidth: 98,
                  fullHeight: 60,
                  aspectRatio: undefined
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__b1Rcd)}
                displayHeight={"60px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"124px"}
                src={{
                  src: "/plasmic/padungsilpa_website/images/lacoste.png",
                  fullWidth: 124,
                  fullHeight: 60,
                  aspectRatio: undefined
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__au2Ij)}
                displayHeight={"60px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"125px"}
                src={{
                  src: "/plasmic/padungsilpa_website/images/levis.png",
                  fullWidth: 125,
                  fullHeight: 60,
                  aspectRatio: undefined
                }}
              />
            </Stack__>
            <Footer
              className={classNames("__wab_instance", sty.footer__kK24D)}
            />
          </div>
          <Stack__
            as={"div"}
            data-plasmic-name={"bigPlants"}
            data-plasmic-override={overrides.bigPlants}
            hasGap={true}
            className={classNames(projectcss.all, sty.bigPlants)}
          >
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__dvmlY)}
            >
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__tGqc
                )}
              >
                <Trans__>{"Big plants"}</Trans__>
              </h2>
            </Stack__>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns___78V)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__at8SM)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__aARl)}
                  displayHeight={"270px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/padungsilpa_website/images/plant6Jpg.png",
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__oVcc4)}>
                  <Icon3Icon
                    className={classNames(projectcss.all, sty.svg__g3OL)}
                    role={"img"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__iGe8G)}>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__ajuKz
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    <Trans__>{"Donec finibus"}</Trans__>
                  </PlasmicLink__>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__sOlcd
                    )}
                  >
                    <Trans__>{"bigplants"}</Trans__>
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__j50J
                    )}
                  >
                    <Trans__>{"$100.00"}</Trans__>
                  </h5>
                </div>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__r7F)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__befGd)}
                  displayHeight={"270px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/padungsilpa_website/images/plant1Jpg.png",
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__kCl6)}>
                  <Icon3Icon
                    className={classNames(projectcss.all, sty.svg__iqZr)}
                    role={"img"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__qefjQ)}>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__dIDfp
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    <Trans__>{"Nulla suscipit"}</Trans__>
                  </PlasmicLink__>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__dVqNi
                    )}
                  >
                    <Trans__>{"bigplants "}</Trans__>
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__jS0J
                    )}
                  >
                    <Trans__>{"$49.40 "}</Trans__>
                  </h5>
                </div>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column___9Xn5V)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img___0U1)}
                  displayHeight={"270px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/padungsilpa_website/images/plant7Jpg.png",
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                <div
                  className={classNames(projectcss.all, sty.freeBox___2KuW0)}
                >
                  <Icon3Icon
                    className={classNames(projectcss.all, sty.svg__zZph8)}
                    role={"img"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__wiDzA)}>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__b3P4H
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    <Trans__>{"Sed consectetur"}</Trans__>
                  </PlasmicLink__>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__s7JnA
                    )}
                  >
                    <Trans__>{"bigplants "}</Trans__>
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__kdpRr
                    )}
                  >
                    <Trans__>{"$18.40 "}</Trans__>
                  </h5>
                </div>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__efNmM)}
                  displayHeight={"270px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/padungsilpa_website/images/plant5Jpg.png",
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__qRmdO)}>
                  <Icon3Icon
                    className={classNames(projectcss.all, sty.svg__nxh37)}
                    role={"img"}
                  />
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox___8PgGs)}
                >
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link___2KZ6J
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    <Trans__>{"Vestibulum eget"}</Trans__>
                  </PlasmicLink__>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qmYbs
                    )}
                  >
                    <Trans__>{"bigplants "}</Trans__>
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5___6Y6UM
                    )}
                  >
                    <Trans__>{"$220.40 "}</Trans__>
                  </h5>
                </div>
              </Stack__>
            </Stack__>
          </Stack__>
          <Stack__
            as={"div"}
            data-plasmic-name={"cactuses"}
            data-plasmic-override={overrides.cactuses}
            hasGap={true}
            className={classNames(projectcss.all, sty.cactuses)}
          >
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__n3Q4C)}
            >
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__spDxT
                )}
              >
                <Trans__>{"Cactuses"}</Trans__>
              </h2>
            </Stack__>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__k5MBz)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__x9E5S)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__thhI)}
                  displayHeight={"270px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/padungsilpa_website/images/plant41Jpg.png",
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__xGiji)}>
                  <Icon3Icon
                    className={classNames(projectcss.all, sty.svg__ybOIh)}
                    role={"img"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__x0N6R)}>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link___4NwWt
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    <Trans__>{"Cras molestie"}</Trans__>
                  </PlasmicLink__>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__oKM0
                    )}
                  >
                    <Trans__>{"cactuses "}</Trans__>
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__iBlW
                    )}
                  >
                    <Trans__>{"$24.99"}</Trans__>
                  </h5>
                </div>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__dp49Q)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__zr526)}
                  displayHeight={"270px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/padungsilpa_website/images/plant31Jpg.png",
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__ys26W)}>
                  <Icon3Icon
                    className={classNames(projectcss.all, sty.svg__saRm7)}
                    role={"img"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__mKBnV)}>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link___2FtV
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    <Trans__>{"Curabitur eu tempor"}</Trans__>
                  </PlasmicLink__>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__czA2X
                    )}
                  >
                    <Trans__>{"Cactuses"}</Trans__>
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__chiqZ
                    )}
                  >
                    <Trans__>{"$49.40 "}</Trans__>
                  </h5>
                </div>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__agRvt)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__mfyex)}
                  displayHeight={"270px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/padungsilpa_website/images/plant9Webp.webp",
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__rEpAa)}>
                  <Icon3Icon
                    className={classNames(projectcss.all, sty.svg__fSzl)}
                    role={"img"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__w81Af)}>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__saMo
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    <Trans__>{"Fusce sagittis"}</Trans__>
                  </PlasmicLink__>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___6Emzj
                    )}
                  >
                    <Trans__>{"Fusce sagittis"}</Trans__>
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__lEnV9
                    )}
                  >
                    <Trans__>{"$49.40 "}</Trans__>
                  </h5>
                </div>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column___9QMkh)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img___0LuQt)}
                  displayHeight={"270px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/padungsilpa_website/images/plant2Webp.webp",
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__gIAdO)}>
                  <Icon3Icon
                    className={classNames(projectcss.all, sty.svg__hITcF)}
                    role={"img"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__ajHx)}>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__d2TZn
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    <Trans__>{"Integer porta"}</Trans__>
                  </PlasmicLink__>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___7OYqA
                    )}
                  >
                    <Trans__>{"Cactuses"}</Trans__>
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__pLoxC
                    )}
                  >
                    <Trans__>{"$49.40 "}</Trans__>
                  </h5>
                </div>
              </Stack__>
            </Stack__>
          </Stack__>
          <div className={classNames(projectcss.all, sty.freeBox__fe3Re)}>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__xFlzA)}
            >
              <h4
                className={classNames(
                  projectcss.all,
                  projectcss.h4,
                  projectcss.__wab_text,
                  sty.h4__vfdCa
                )}
              >
                <Trans__>{"How long does shipping take?"}</Trans__>
              </h4>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__fXqOv
                )}
              >
                <Trans__>
                  {hasVariant(globalVariants, "screen", "mobile")
                    ? "I didn't know the Snipcart guys were into herbs as well! How beautiful is that Planty theme. I'm going to launch a killer JAMstack e-commerce store using this for sure."
                    : "Now that\u2019s a frequent one all right, ain\u2019t it? Your answer to this should manage customer expectations. Just like a good checkout flow should. Tell them the truth"}
                </Trans__>
              </div>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__efFFv)}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__n7De5)}
                >
                  <DotSvgrepoCom1SvgIcon
                    className={classNames(projectcss.all, sty.svg__io32Y)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___6BLMg
                    )}
                  >
                    <Trans__>
                      {"US shipping will take between 3 to 5 business days."}
                    </Trans__>
                  </div>
                </Stack__>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__iSCnk)}
                >
                  <DotSvgrepoCom1SvgIcon
                    className={classNames(projectcss.all, sty.svg__jfCsM)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__e4Qsb
                    )}
                  >
                    <Trans__>
                      {
                        "International shipping will take between 5 and 10 business days."
                      }
                    </Trans__>
                  </div>
                </Stack__>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__fQt5H)}
                >
                  <DotSvgrepoCom1SvgIcon
                    className={classNames(projectcss.all, sty.svg__cf4Jv)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___0EbFi
                    )}
                  >
                    <Trans__>
                      {
                        "Mars shipping will be automatically redirected to Elon Musk\u2019s Twitter account."
                      }
                    </Trans__>
                  </div>
                </Stack__>
              </Stack__>
            </Stack__>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__hvXo)}
            >
              <h4
                className={classNames(
                  projectcss.all,
                  projectcss.h4,
                  projectcss.__wab_text,
                  sty.h4__yclqm
                )}
              >
                <Trans__>{"How do refunds and returns work?"}</Trans__>
              </h4>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ctwIs
                )}
              >
                <Trans__>
                  {hasVariant(globalVariants, "screen", "mobile")
                    ? "I didn't know the Snipcart guys were into herbs as well! How beautiful is that Planty theme. I'm going to launch a killer JAMstack e-commerce store using this for sure."
                    : "It happens. Even the most beautiful of plants will disappoint someone. Again, tell it like it is:"}
                </Trans__>
              </div>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox___68Pq)}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__sko1Y)}
                >
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__l5Pia)}
                  >
                    <DotSvgrepoCom1SvgIcon
                      className={classNames(projectcss.all, sty.svg__d5Sm5)}
                      role={"img"}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__kPksE
                      )}
                    >
                      <Trans__>
                        {"All discounted items sales are final."}
                      </Trans__>
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__bNavi)}
                  >
                    <DotSvgrepoCom1SvgIcon
                      className={classNames(projectcss.all, sty.svg___1JlJc)}
                      role={"img"}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___6ZjDd
                      )}
                    >
                      <Trans__>
                        {
                          "If you\u2019d like another version of your item, please use the return label. Instructions are printed on its back."
                        }
                      </Trans__>
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__k3OwM)}
                  >
                    <DotSvgrepoCom1SvgIcon
                      className={classNames(projectcss.all, sty.svg__u7KU)}
                      role={"img"}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___8IgUx
                      )}
                    >
                      <Trans__>
                        {
                          "If your item is damaged or not functioning correctly, email us at info@planty.com, and we\u2019ll refund you + send you a new one ASAP!"
                        }
                      </Trans__>
                    </div>
                  </Stack__>
                </Stack__>
              </Stack__>
            </Stack__>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__xc727)}
            >
              <h4
                className={classNames(
                  projectcss.all,
                  projectcss.h4,
                  projectcss.__wab_text,
                  sty.h4___5W92Y
                )}
              >
                <Trans__>{"Rapid-fire questions"}</Trans__>
              </h4>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___3WJ0
                )}
              >
                <Trans__>
                  {hasVariant(globalVariants, "screen", "mobile")
                    ? "I didn't know the Snipcart guys were into herbs as well! How beautiful is that Planty theme. I'm going to launch a killer JAMstack e-commerce store using this for sure."
                    : "GDPR, am I right? Make sure you\u2019re as transparent as possible with your data handling process. Or, if you\u2019re using Snipcart, just refer to our ToS and DPA"}
                </Trans__>
              </div>
            </Stack__>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__pasXn)}
            >
              <h4
                className={classNames(
                  projectcss.all,
                  projectcss.h4,
                  projectcss.__wab_text,
                  sty.h4__nl4My
                )}
              >
                <Trans__>
                  {"How do you handle sensitive customer information?"}
                </Trans__>
              </h4>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__oyZxR
                )}
              >
                <Trans__>
                  {hasVariant(globalVariants, "screen", "mobile")
                    ? "I didn't know the Snipcart guys were into herbs as well! How beautiful is that Planty theme. I'm going to launch a killer JAMstack e-commerce store using this for sure."
                    : "GDPR, am I right? Make sure you\u2019re as transparent as possible with your data handling process. Or, if you\u2019re using Snipcart, just refer to our ToS and DPA"}
                </Trans__>
              </div>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__plcqv)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__zEj0Z)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__mHfbx
                    )}
                  >
                    <Trans__>
                      {"Q: Why is this Planty theme so beautiful?"}
                    </Trans__>
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__nq24Z
                    )}
                  >
                    <Trans__>
                      {"A: We hired our first designer a couple of months ago."}
                    </Trans__>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__vhg8)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__uA8E
                    )}
                  >
                    <Trans__>
                      {"Q: Why did you build a theme for Stackbit?"}
                    </Trans__>
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__afPtd
                    )}
                  >
                    <Trans__>
                      {
                        "A: We believe in Stackbit\u2019s promise of opening up the JAMstack to more developers. Plus, we trust these folks.\n Read more about Stackbit"
                      }
                    </Trans__>
                  </div>
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox___5Y7A2)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qiq3I
                    )}
                  >
                    <Trans__>{"Q: How many people work at Snipcart? "}</Trans__>
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ieHo
                    )}
                  >
                    <Trans__>
                      {
                        "A: Not a lot! We\u2019re a small, bootstrapped team of eight human beings. Michael might be a robot, though. "
                      }
                    </Trans__>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__cVWkT)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__cNfVb
                    )}
                  >
                    <Trans__>
                      {"Q: Why is Snipcart based in Qu\u00e9bec City?"}
                    </Trans__>
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__yk70
                    )}
                  >
                    <Trans__>
                      {"A: Have you been here? It\u2019s beaaautiful!"}
                    </Trans__>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__qDeXn)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__eCSf5
                    )}
                  >
                    <Trans__>{"Q: What\u2019s the meaning of life? "}</Trans__>
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__v4Ky6
                    )}
                  >
                    <Trans__>
                      {
                        "A: We\u2019re not quite sure. But building useful products with people we love feels meaningful enough."
                      }
                    </Trans__>
                  </div>
                </div>
              </Stack__>
            </Stack__>
          </div>
          <Footer className={classNames("__wab_instance", sty.footer__yFjbe)} />

          <div className={classNames(projectcss.all, sty.freeBox__tDhWi)}>
            <div className={classNames(projectcss.all, sty.freeBox__ksIb)}>
              <div className={classNames(projectcss.all, sty.columns__q8Xn)}>
                <div className={classNames(projectcss.all, sty.column__rgwCh)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___8XePq)}
                    displayHeight={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? "562px"
                        : "562px"
                    }
                    displayMaxHeight={"none"}
                    displayMaxWidth={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? "100%"
                        : "100%"
                    }
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? "947px"
                        : "947px"
                    }
                    loading={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? "lazy"
                        : "lazy"
                    }
                    src={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? {
                            src: "/plasmic/padungsilpa_website/images/promoWebp.webp",
                            fullWidth: 720,
                            fullHeight: 525,
                            aspectRatio: undefined
                          }
                        : {
                            src: "/plasmic/padungsilpa_website/images/promoWebp.webp",
                            fullWidth: 720,
                            fullHeight: 525,
                            aspectRatio: undefined
                          }
                    }
                  />
                </div>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column__ixel)}
                >
                  <h1
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1__nlNAf
                    )}
                  >
                    <Trans__>
                      {hasVariant(globalVariants, "screen", "mobile")
                        ? "Behold our FAQ"
                        : "Still have questions?\nContact us. "}
                    </Trans__>
                  </h1>
                  <div
                    className={classNames(projectcss.all, sty.columns__uZvS)}
                  >
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.column__tszo9)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___2Eftb
                        )}
                      >
                        <Trans__>
                          {hasVariant(globalVariants, "screen", "mobile")
                            ? "Behold our FAQ"
                            : "226 rue St-Joseph E, \nQu\u00e9bec, QC, Canada, \nG1K 3A9"}
                        </Trans__>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__cmNSd
                        )}
                      >
                        <Trans__>
                          {hasVariant(globalVariants, "screen", "mobile")
                            ? "Behold our FAQ"
                            : "+1-202-555-0112"}
                        </Trans__>
                      </div>
                    </Stack__>
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.column__cqE5)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__o5BYh
                        )}
                      >
                        <Trans__>
                          {hasVariant(globalVariants, "screen", "mobile")
                            ? "Behold our FAQ"
                            : "geeks@snipcart.com"}
                        </Trans__>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___1M6LA
                        )}
                      >
                        <Stack__
                          as={PlasmicLink__}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            sty.link___3F8Z
                          )}
                          component={Link}
                          platform={"nextjs"}
                        >
                          <LocationSvgrepoCom1SvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__qp6Y
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___5St0K
                            )}
                          >
                            <Trans__>
                              {hasVariant(globalVariants, "screen", "mobile")
                                ? "Discover"
                                : "On the map"}
                            </Trans__>
                          </div>
                        </Stack__>
                      </div>
                    </Stack__>
                  </div>
                </Stack__>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__c7SPb)}>
              <div className={classNames(projectcss.all, sty.freeBox__mdjDl)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__m56CX)}
                >
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox___4FE)}
                  >
                    <MenuButton
                      data-plasmic-name={"menuButton"}
                      data-plasmic-override={overrides.menuButton}
                      className={classNames("__wab_instance", sty.menuButton)}
                    />

                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox___6CfD)}
                    >
                      <PlasmicIcon__
                        PlasmicIconType={
                          hasVariant(globalVariants, "screen", "mobile")
                            ? LogoWhiteSvgIcon
                            : LogoWhiteSvgIcon
                        }
                        className={classNames(projectcss.all, sty.svg__c9WXc)}
                        role={"img"}
                      />

                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__zqHkw
                        )}
                        component={Link}
                        href={
                          hasVariant(globalVariants, "screen", "mobile")
                            ? "#"
                            : `/store`
                        }
                        platform={"nextjs"}
                      >
                        <Trans__>
                          {hasVariant(globalVariants, "screen", "mobile")
                            ? "Store"
                            : "Store"}
                        </Trans__>
                      </PlasmicLink__>
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__cLY7
                        )}
                        component={Link}
                        href={
                          hasVariant(globalVariants, "screen", "mobile")
                            ? "#"
                            : `/about`
                        }
                        platform={"nextjs"}
                      >
                        <Trans__>
                          {hasVariant(globalVariants, "screen", "mobile")
                            ? "About"
                            : "About"}
                        </Trans__>
                      </PlasmicLink__>
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__k79Um
                        )}
                        component={Link}
                        href={
                          hasVariant(globalVariants, "screen", "mobile")
                            ? "#"
                            : `/faq`
                        }
                        platform={"nextjs"}
                      >
                        <Trans__>
                          {hasVariant(globalVariants, "screen", "mobile")
                            ? "Faq"
                            : "Faq"}
                        </Trans__>
                      </PlasmicLink__>
                    </Stack__>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__bAAeE)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__iaqJg
                        )}
                      >
                        <Trans__>
                          {hasVariant(globalVariants, "screen", "mobile")
                            ? "\u00a9 Company. All rights reserved. This site proudly built with "
                            : "\u00a9 Company. All rights reserved. This site proudly built with "}
                        </Trans__>
                      </div>
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__ixPl9
                        )}
                        component={Link}
                        href={
                          hasVariant(globalVariants, "screen", "mobile")
                            ? "https://www.plasmic.app/"
                            : "https://www.plasmic.app/"
                        }
                        platform={"nextjs"}
                      >
                        <Trans__>
                          {hasVariant(globalVariants, "screen", "mobile")
                            ? "Plasmic"
                            : "Plasmic"}
                        </Trans__>
                      </PlasmicLink__>
                    </div>
                  </Stack__>
                </Stack__>
              </div>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "foreground2",
    "header",
    "featureItem",
    "bigPlants",
    "cactuses",
    "menuButton"
  ],
  foreground2: ["foreground2"],
  header: ["header", "featureItem"],
  featureItem: ["featureItem"],
  bigPlants: ["bigPlants"],
  cactuses: ["cactuses"],
  menuButton: ["menuButton"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  foreground2: "div";
  header: "div";
  featureItem: typeof FeatureItem;
  bigPlants: "div";
  cactuses: "div";
  menuButton: typeof MenuButton;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicFaq__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicFaq__VariantsArgs;
    args?: PlasmicFaq__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicFaq__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicFaq__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicFaq__ArgProps,
          internalVariantPropNames: PlasmicFaq__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicFaq__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFaq";
  } else {
    func.displayName = `PlasmicFaq.${nodeName}`;
  }
  return func;
}

export const PlasmicFaq = Object.assign(
  // Top-level PlasmicFaq renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    foreground2: makeNodeComponent("foreground2"),
    header: makeNodeComponent("header"),
    featureItem: makeNodeComponent("featureItem"),
    bigPlants: makeNodeComponent("bigPlants"),
    cactuses: makeNodeComponent("cactuses"),
    menuButton: makeNodeComponent("menuButton"),

    // Metadata about props expected for PlasmicFaq
    internalVariantProps: PlasmicFaq__VariantProps,
    internalArgProps: PlasmicFaq__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicFaq;
/* prettier-ignore-end */
