// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qoVKgVQ2sZgJYceYTt4HBN
// Component: ts7fEiC7or6S

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic.module.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: qoVKgVQ2sZgJYceYTt4HBN/projectcss
import sty from "./PlasmicRatings.module.css"; // plasmic-import: ts7fEiC7or6S/css

import StarIcon from "./icons/PlasmicIcon__Star"; // plasmic-import: KZvr0d77Lnbp/icon

createPlasmicElementProxy;

export type PlasmicRatings__VariantMembers = {
  stars: "zero" | "one" | "two" | "three" | "four" | "five";
};
export type PlasmicRatings__VariantsArgs = {
  stars?: SingleChoiceArg<"zero" | "one" | "two" | "three" | "four" | "five">;
};
type VariantPropType = keyof PlasmicRatings__VariantsArgs;
export const PlasmicRatings__VariantProps = new Array<VariantPropType>("stars");

export type PlasmicRatings__ArgsType = {
  numReviews?: React.ReactNode;
};
type ArgPropType = keyof PlasmicRatings__ArgsType;
export const PlasmicRatings__ArgProps = new Array<ArgPropType>("numReviews");

export type PlasmicRatings__OverridesType = {
  root?: Flex__<"div">;
  freeBox?: Flex__<"div">;
};

export interface DefaultRatingsProps {
  numReviews?: React.ReactNode;
  stars?: SingleChoiceArg<"zero" | "one" | "two" | "three" | "four" | "five">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicRatings__RenderFunc(props: {
  variants: PlasmicRatings__VariantsArgs;
  args: PlasmicRatings__ArgsType;
  overrides: PlasmicRatings__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $translator = usePlasmicTranslator?.();

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "stars",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.stars
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  return (
    <Stack__
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_library_plasmic_color_type_css.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        sty.root,
        {
          [sty.rootstars_five]: hasVariant($state, "stars", "five"),
          [sty.rootstars_four]: hasVariant($state, "stars", "four"),
          [sty.rootstars_one]: hasVariant($state, "stars", "one"),
          [sty.rootstars_three]: hasVariant($state, "stars", "three"),
          [sty.rootstars_two]: hasVariant($state, "stars", "two"),
          [sty.rootstars_zero]: hasVariant($state, "stars", "zero")
        }
      )}
    >
      <Stack__
        as={"div"}
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox)}
      >
        <StarIcon
          className={classNames(projectcss.all, sty.svg__eqkt, {
            [sty.svgstars_five__eqktvc9Cl]: hasVariant($state, "stars", "five"),
            [sty.svgstars_zero__eqktbBuYu]: hasVariant($state, "stars", "zero")
          })}
          role={"img"}
        />

        <StarIcon
          className={classNames(projectcss.all, sty.svg___23CFi, {
            [sty.svgstars_five___23CFiVc9Cl]: hasVariant(
              $state,
              "stars",
              "five"
            ),
            [sty.svgstars_four___23CFiop0Ui]: hasVariant(
              $state,
              "stars",
              "four"
            ),
            [sty.svgstars_one___23CFimS9HI]: hasVariant($state, "stars", "one"),
            [sty.svgstars_three___23CFiv54V]: hasVariant(
              $state,
              "stars",
              "three"
            ),
            [sty.svgstars_two___23CFiR093]: hasVariant($state, "stars", "two"),
            [sty.svgstars_zero___23CFiBBuYu]: hasVariant(
              $state,
              "stars",
              "zero"
            )
          })}
          role={"img"}
        />

        <StarIcon
          className={classNames(projectcss.all, sty.svg__lNk3, {
            [sty.svgstars_five__lNk3Vc9Cl]: hasVariant($state, "stars", "five"),
            [sty.svgstars_four__lNk3Op0Ui]: hasVariant($state, "stars", "four"),
            [sty.svgstars_one__lNk3MS9HI]: hasVariant($state, "stars", "one"),
            [sty.svgstars_three__lNk3V54V]: hasVariant(
              $state,
              "stars",
              "three"
            ),
            [sty.svgstars_two__lNk3R093]: hasVariant($state, "stars", "two"),
            [sty.svgstars_zero__lNk3BBuYu]: hasVariant($state, "stars", "zero")
          })}
          role={"img"}
        />

        <StarIcon
          className={classNames(projectcss.all, sty.svg__dCyMf, {
            [sty.svgstars_five__dCyMfvc9Cl]: hasVariant(
              $state,
              "stars",
              "five"
            ),
            [sty.svgstars_four__dCyMFop0Ui]: hasVariant(
              $state,
              "stars",
              "four"
            ),
            [sty.svgstars_one__dCyMFmS9HI]: hasVariant($state, "stars", "one"),
            [sty.svgstars_three__dCyMFv54V]: hasVariant(
              $state,
              "stars",
              "three"
            ),
            [sty.svgstars_two__dCyMfr093]: hasVariant($state, "stars", "two"),
            [sty.svgstars_zero__dCyMfbBuYu]: hasVariant($state, "stars", "zero")
          })}
          role={"img"}
        />

        <StarIcon
          className={classNames(projectcss.all, sty.svg___51BvS, {
            [sty.svgstars_five___51BvSvc9Cl]: hasVariant(
              $state,
              "stars",
              "five"
            ),
            [sty.svgstars_four___51BvSop0Ui]: hasVariant(
              $state,
              "stars",
              "four"
            ),
            [sty.svgstars_one___51BvSmS9HI]: hasVariant($state, "stars", "one"),
            [sty.svgstars_three___51BvSv54V]: hasVariant(
              $state,
              "stars",
              "three"
            ),
            [sty.svgstars_two___51BvSr093]: hasVariant($state, "stars", "two"),
            [sty.svgstars_zero___51BvSbBuYu]: hasVariant(
              $state,
              "stars",
              "zero"
            )
          })}
          role={"img"}
        />

        <StarIcon
          className={classNames(projectcss.all, sty.svg__lwowA, {
            [sty.svgstars_five__lwowAvc9Cl]: hasVariant(
              $state,
              "stars",
              "five"
            ),
            [sty.svgstars_four__lwowAop0Ui]: hasVariant(
              $state,
              "stars",
              "four"
            ),
            [sty.svgstars_one__lwowAmS9HI]: hasVariant($state, "stars", "one"),
            [sty.svgstars_three__lwowAv54V]: hasVariant(
              $state,
              "stars",
              "three"
            ),
            [sty.svgstars_two__lwowAr093]: hasVariant($state, "stars", "two"),
            [sty.svgstars_zero__lwowAbBuYu]: hasVariant($state, "stars", "zero")
          })}
          role={"img"}
        />

        <StarIcon
          className={classNames(projectcss.all, sty.svg___5LbJe, {
            [sty.svgstars_five___5LbJeVc9Cl]: hasVariant(
              $state,
              "stars",
              "five"
            ),
            [sty.svgstars_four___5LbJeop0Ui]: hasVariant(
              $state,
              "stars",
              "four"
            ),
            [sty.svgstars_three___5LbJev54V]: hasVariant(
              $state,
              "stars",
              "three"
            ),
            [sty.svgstars_two___5LbJeR093]: hasVariant($state, "stars", "two")
          })}
          role={"img"}
        />

        <StarIcon
          className={classNames(projectcss.all, sty.svg__vgJW, {
            [sty.svgstars_five__vgJWvc9Cl]: hasVariant($state, "stars", "five"),
            [sty.svgstars_four__vgJWop0Ui]: hasVariant($state, "stars", "four"),
            [sty.svgstars_three__vgJWv54V]: hasVariant($state, "stars", "three")
          })}
          role={"img"}
        />

        <StarIcon
          className={classNames(projectcss.all, sty.svg__sa9Ow, {
            [sty.svgstars_five__sa9OwVc9Cl]: hasVariant(
              $state,
              "stars",
              "five"
            ),
            [sty.svgstars_four__sa9Owop0Ui]: hasVariant($state, "stars", "four")
          })}
          role={"img"}
        />

        <StarIcon
          className={classNames(projectcss.all, sty.svg__fGd7D, {
            [sty.svgstars_five__fGd7Dvc9Cl]: hasVariant($state, "stars", "five")
          })}
          role={"img"}
        />
      </Stack__>
      {renderPlasmicSlot({
        defaultContents: <Trans__>{"(45 Review)"}</Trans__>,
        value: args.numReviews,
        className: classNames(sty.slotTargetNumReviews)
      })}
    </Stack__>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "freeBox"],
  freeBox: ["freeBox"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  freeBox: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicRatings__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicRatings__VariantsArgs;
    args?: PlasmicRatings__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicRatings__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicRatings__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicRatings__ArgProps,
          internalVariantPropNames: PlasmicRatings__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicRatings__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicRatings";
  } else {
    func.displayName = `PlasmicRatings.${nodeName}`;
  }
  return func;
}

export const PlasmicRatings = Object.assign(
  // Top-level PlasmicRatings renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),

    // Metadata about props expected for PlasmicRatings
    internalVariantProps: PlasmicRatings__VariantProps,
    internalArgProps: PlasmicRatings__ArgProps
  }
);

export default PlasmicRatings;
/* prettier-ignore-end */
